#spring:
#  application:
#    name: gulimall-search
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  thymeleaf:
#    cache: false
#  redis:
#    host: 192.168.52.128
#    port: 6379
#  session:
#    store-type: redis
#
#server:
#  port: 10007
#
#gulimall:
#  elasticsearch:
#    host: 192.168.52.128
#    port: 9200
