spring:
  application:
    name: gulimall-third-party
  cloud:
    alicloud:
      access-key: LTAI4GEEH4Asm83pNRUMd1S5
      secret-key: OCTLZA2FFuRDvUPRYQ6KoyUsMEORxy
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: yanmall
      sms:
        host: http://smsmsgs.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 1
        appcode:

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9006
