spring:
  application:
    name: gulimall-third-party
  cloud:
    alicloud:
      access-key: LTAI4GEEH4Asm83pNRUMd1S5
      secret-key: OCTLZA2FFuRDvUPRYQ6KoyUsMEORxy
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: yanmall
      sms:
        host: https://feginesms.market.alicloudapi.com
        path: /codeNotice
        skin: 1
        sign: 1
        appcode: 5d70ca0a3db34815a55a1c806a4024f2

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 192.168.52.128
  session:
    store-type: redis

alipay:
  app-id: 2016102700772599
  gateway-url: https://openapi.alipaydev.com/gateway.do
  merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6alzb2F+lutaF/KfzcpJZgZGsDjC+WPeQIuk2nP1tepROscpN42IgZav5vEmbr91KirZHyyHI/pqOF5BTn6IUvoChk7nrGRzQMtlx1tz/exzZ+4yf4rO8HZSbXAzG9g9Wq6HfRQlqtlLN2qPHA/k4cDOHPemn/ivFqEiaYTms7b/5qUtA7G8LU84GSNOvc5bp3DSGUiRV9wQUQliQUNrzBLjA1DaWao3hru3oJp3AbF2oFF3KInFg/S4g7fBCA1/OPCbkWDPsxsRWJIfGTg/QNXK7ghnp6toiwGZWFH++5wcs61fpIDXd8MfIewBGFFUFNIql0xbsjFMHjpub+xflAgMBAAECggEAS6rk6nAX0wPWFCkMW2tEMITBhp9z9a/TPXSOSZbL3+aD0LWmMpt7tz7N4d8l2cY3AwzvFJFFs3p1bfvun6MKfXUebXezXdSht3kMfoMCzclBWtIasMOqxU8UhUOGBDTY4Qtl92Tkf6ZmUhzPofbg8KHKqLje4UvwpJi8b73LVX+yp6gsnevSmGYVf33U4gS0Egrfhi+SACYe6IpusVd5hLzEFR+rHZbQeSva2Oc1KwJhUplz2Q8tk5vAM6Vapp0IsDkdfh39vsR4qJW1+EsNu9dVdGVreDJfspzfEEvR2ZrkB27HVyGbc15NGC0OuPrvLO5TVDN6NG1R7noxQ7K6QQKBgQDgEAP9jT7R8CWQxgdWi9LeJLBSQkkYcCeoNdp1XRyi5Zii2nn5+gR4nRyjWmhx+CRhE24XqEBILD8pcBf7KlX91BDalOS/tZuluwKaQUnLYKe0MBUZbQtN4XxwLJIXUCHpOePNapg+Rxm14+bD2uvYGY/vEz5Gg+4C1Wq3EqvguQKBgQDU/J1t0tqC3u6XbP3VSlY8fLyzMox/3JIHXphRyyekgWF0GBaaBa3B0H3Z4FlbND15ijXZjpQq1ZzH+StGaPWBuN33uoZzpmmA6GeEuK8jl6JdQVsuR4DzlLG/adLC6rYgmi3VnWm0ratHfYL7et3i6O8b7G+u8IsBYfeNBdXijQKBgQCzYn8fXxbdU2tv5et4EcfIDA2SPflxdFF7rWnyLpK/pBu4vjuLs+wieH62FaqrHCRcCAdLL2wPnEURMuowLuvbpQ29QhmFlqs/W2KxBvZCumZpr1klGxVCy/UphbWMrp4HsE4+ZknvClN+OTDGux24zHZczMY+BF/oqt6eJXewGQKBgBSCiwpzXpVxsFompb7vXKSQgn9jI8KAVBOfmV1vCc8+okrSswJ7/4KFeEkN4Kz2t+DHXW4o273QOjvLk85A9ztZuQ5NCPuED+7Y8ncGbd8oj/sY+xXWzuUl8YP0RdZ9UbKMBlPmx7Idczv8KyvaZhmewr/Wod6fzVMBwxvybulVAoGAW7sJ2tteQy6pY3pgvrZOVGmH9iurgJV/fDSDbu8sMKLnnm6Xh3NSo11y+QReIO354J3TixAwSYydEB8D0pA0PIcbGDS75qTXm/KcS6XmbfLov+9M6PaZunPjfgOooate7MJwR3MnlRnOM5l0Bq7fmsaPyvpyekb0fss3jRa1AhE=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjAaJZGmA/UnlboI3dOfSM24Ui93CvKU6DTnBfySVYpp/QepVQNBlWQuOmhPMKYUhQyWGGYkGAMzFffjobSSv4c8oKeoF/pjPxPejvOLONIvUxeRNaBal3cuBl3XI2e0mchcwXCS1sA9yolEQQVuo3M5qeZ+Kk3+QQYd/dUSS8QgIrIbGlAz/WWBlhkZfA5w8GcLiaxm4DnU7koWVdpBV0h3L7s5/q/1giu5Q8gmUyT2ZNQBTcWlLQqMGxGMujCq1JmKzjraStUY1xsIuPm8b+U1tfY/qHF6BFh2Xnrdo6dhmeW7RbIoukeoPFGgEadfZZ8CeLEFCHcdC9RzQoMt0BQIDAQAB
  notify-url: http://localhost/payed/notify
  return-url: http://member.gulimall.com/memberOder.html



server:
  port: 10007
