spring:
  application:
    name: gulimall-gateway
  zipkin:
    base-url: http://10.211.55.20:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
    gateway:
      routes:
        - id: gulimall_cart_route1
          uri: lb://gulimall-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/cart/v2/api-docs,/v2/api-docs
            - RewritePath=/api/(?<sement>.*),/$\{sement}
        - id: gulimall_auth_route1
          uri: lb://gulimall-auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/v2/api-docs,/v2/api-docs
            - RewritePath=/api/(?<sement>.*),/$\{sement}
        - id: gulimall_order_route1
          uri: lb://gulimall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/v2/api-docs,/v2/api-docs
            - RewritePath=/api/(?<sement>.*),/$\{sement}
        - id: gulimall_search_route1
          uri: lb://gulimall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/search/v2/api-docs,/v2/api-docs
        - id: gulimall_seckill_route1
          uri: lb://gulimall-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - RewritePath=/api/seckill/v2/api-docs,/v2/api-docs
        - id: gulimall_ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/ware/v2/api-docs,/v2/api-docs
            - RewritePath=/api/(?<sement>.*),/$\{sement}
        - id: gulimall_coupon_route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/coupon/v2/api-docs,/v2/api-docs
            - RewritePath=/api/(?<sement>.*),/$\{sement}
        - id: gulimall_member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/member/v2/api-docs,/v2/api-docs
            - RewritePath=/api/(?<sement>.*),/$\{sement}
        - id: gulimall_product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/v2/api-docs,/v2/api-docs
            - RewritePath=/api/(?<sement>.*),/$\{sement}
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/v2/api-docs,/v2/api-docs
            - RewritePath=/api/thirdparty/(?<sement>.*),/$\{sement}
        - id: admin_rote
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<sement>.*),/renren-fast/$\{sement}
        - id: gulimall_seckill_route
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com
        - id: gulimall_member_route
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com
        - id: gulimall_order_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com
        - id: gulimall_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com
        - id: gulimall_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com
        - id: gulimall_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        - id: gulimall_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com



server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.yanlaoge.gulimall: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

